name: cabgo_driver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  easy_debounce: ^2.0.2+1
  flutter_credit_card: ^3.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  location: ^4.4.0
  google_maps_flutter: ^2.1.6
  intl: ^0.17.0
  json_path: ^0.4.0
  page_transition: ^2.0.5
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.2.2
  url_launcher: ^6.1.2
  uuid: ^3.0.6
  geolocator: ^8.2.1
  google_maps_webservice: ^0.0.19
  http: ^0.13.4
  geocoding: ^2.0.4
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.0
  flutter_google_places: ^0.3.0
  geocode: 1.0.1
  google_api_headers: ^1.3.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2
  go_router: ^3.1.1
  percent_indicator: 4.0.0
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter_ringtone_player: ^3.2.0
  swipeable_button_view: ^0.0.2
  dependencies:
  swipebuttonflutter: ^1.0.0
  permission_handler: ^8.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  lite_rolling_switch: ^0.1.1
  slider_button: ^2.0.0
  fswitch_nullsafety: ^2.0.2
  rating_dialog: ^2.0.4
  device_info_plus: ^4.0.0
  image_picker: ^0.8.5+3
  colorful_safe_area: ^0.3.0
  flutter_native_splash: ^2.2.0+1
  screen_loader: ^4.0.1
  progress_dialog: ^1.2.4
  flutter_share: ^2.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/BLACK_CABGO_LOGO.png


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/cg_logo.png"
  adaptive_icon_foreground: "assets/images/cg_launcher.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - .env

